JLLF.Presentation/ViewModels/SchedulingViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace JLLF.Presentation.ViewModels
{
    public class SchedulingViewModel
    {
        public int? Id { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório!")]
        [Range(1, 999999999)]
        public int IdCollaboratorViewModel { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório!")]
        [Range(1, 999999999)]
        public int IdCustomerViewModel { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório!")]
        [Range(1, 999999999)]
        public int IdServiceProvidedViewModel { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório!")]
        public DateTime DateTime { get; set; }

        public bool? Status { get; set; }
    }

    public class ResponseSchedulingViewModel : SchedulingViewModel
    {
        public virtual CollaboratorViewModel CollaboratorViewModel { get; set; }
        public virtual CustomerViewModel CustomerViewModel { get; set; }
        public virtual ServiceProvidedViewModel ServiceProvidedViewModel { get; set; }
    }
}

JLLF.Presentation/Controllers/SchedulingsController.cs
using JLLF.Domain.Interfaces.Services;
using JLLF.Domain.Validations;
using JLLF.Presentation.Mappings;
using JLLF.Presentation.Mappings.Responses;
using JLLF.Presentation.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace JLLF.Presentation.Controllers
{
    public class SchedulingsController : Controller
    {
        private readonly ISchedulingService _schedulingService;
        private readonly CompositeViewModelMapping compositeViewModelMapping = new();
        private readonly ResponseSchedulingViewModelMapping responseSchedulingViewModelMapping = new();

        public SchedulingsController(ISchedulingService schedulingService)
        {
            _schedulingService = schedulingService;
        }

        public IActionResult Index()
        {
            try
            {
                ViewBag.message = TempData["message"] as string;

                IList<ResponseSchedulingViewModel> responseSchedulingViewModels = responseSchedulingViewModelMapping.ListConversion(_schedulingService.FindAll());

                if (responseSchedulingViewModels.Count > 0)
                    return View(responseSchedulingViewModels);

                return RedirectToAction("Create");
            }
            catch (Exception)
            {
                return RedirectToAction("Create");
            }
        }

        public IActionResult Create()
        {
            try
            {
                CompositeViewModel compositeViewModel = compositeViewModelMapping.Conversion(_schedulingService.FindAllCollaboratorsAndCustomersAndServicesProvided());

                if (compositeViewModel != null)
                    return View(compositeViewModel);

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Create(CompositeViewModel compositeViewModel)
        {
            if (ModelState.IsValid)
            {
                compositeViewModel.Status = false;

                _schedulingService.Create<SchedulingValidation>(compositeViewModelMapping.Conversion(compositeViewModel));

                TempData["message"] = "Agendamento marcado com sucesso!".ToString();

                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Update(int id)
        {
            try
            {
                CompositeViewModel compositeViewModel = compositeViewModelMapping.ConversionAll(_schedulingService.FindCollaboratorAndCustomerAndSchedulingAndServiceProvidedById(id));

                if (compositeViewModel != null)
                    return View(compositeViewModel);

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Update(CompositeViewModel compositeViewModel)
        {
            if (ModelState.IsValid)
            {
                compositeViewModel.Status = false;

                _schedulingService.Update<SchedulingValidation>(compositeViewModelMapping.Conversion(compositeViewModel));

                TempData["message"] = "Agendamento remarcado com sucesso!".ToString();

                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult UpdateStatus(int id)
        {
            try
            {
                CompositeViewModel compositeViewModel = compositeViewModelMapping.ConversionAll(_schedulingService.FindCollaboratorAndCustomerAndSchedulingAndServiceProvidedById(id));

                if (compositeViewModel != null)
                    return View(compositeViewModel);

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult UpdateStatus(CompositeViewModel compositeViewModel)
        {
            if (ModelState.IsValid)
            {
                compositeViewModel.Status = true;

                _schedulingService.Update<SchedulingValidation>(compositeViewModelMapping.Conversion(compositeViewModel));

                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

JLLF.Presentation/Views/Schedulings/Create.cshtml
@model JLLF.Presentation.ViewModels.CompositeViewModel

@{
    ViewData["Title"] = "Agendamento";
}

<label style="font-weight:bold">Inserir Agendamento</label>

<br />
<br />

<form asp-controller="Schedulings" asp-action="Create">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Colaborador</label>
            <select asp-for="IdCollaboratorViewModel" class="form-control">
                @{
                    foreach (var item in Model.ResponseCollaboratorsViewModel)
                    {
                        <option value="@item.Id">@item.Name</option>
                    }
                }
            </select>
        </div>
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Cliente</label>
            <select asp-for="IdCustomerViewModel" class="form-control">
                @{
                    foreach (var item in Model.ResponseCustomersViewModel)
                    {
                        <option value="@item.Id">@item.Name</option>
                    }
                }
            </select>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Serviço</label>
            <select asp-for="IdServiceProvidedViewModel" class="form-control">
                @{
                    foreach (var item in Model.ResponseServicesProvidedViewModel)
                    {
                        <option value="@item.Id">@item.Description</option>
                    }
                }
            </select>
        </div>
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Data e Horário</label>
            <input asp-for="DateTime" class="form-control" type="datetime-local" required value="@DateTime.Now" />
            <span asp-validation-for="DateTime" class="text-danger" style="font-weight:bold"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12">
            <button class="btn btn-outline-warning btn-block" type="submit" style="font-weight:bold">Salvar</button>
        </div>
    </div>
</form>

JLLF.Presentation/Views/Schedulings/Index.cshtml
@model IList<JLLF.Presentation.ViewModels.ResponseSchedulingViewModel>

@{
    ViewData["Title"] = "Agendamentos";
}

<label style="font-weight:bold">Agendamentos</label>

<br />
<br />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css" />

<table class="table table-responsive-sm">
    <thead>
        <tr>
            <th style="display:none">Código</th>
            <th>Colaborador</th>
            <th>Cliente</th>
            <th>Serviço</th>
            <th>Data</th>
            <th>Horário</th>
            <th>Status</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var item in Model)
            {
                <tr>
                    <td style="display:none">@item.Id</td>
                    <td>@item.CollaboratorViewModel.Name</td>
                    <td>@item.CustomerViewModel.Name</td>
                    <td>@item.ServiceProvidedViewModel.Description</td>
                    <td>@item.DateTime.Date.ToShortDateString()</td>
                    <td>@item.DateTime.TimeOfDay</td>
                    @if (@item.Status == true)
                     {
                        <td>Atendido</td>
                     }
                     else
                     {
                        <td>Aguardando</td>
                     }
                    <td>
                        <button class="btn btn-outline-warning btn-sm" type="button" style="font-weight:bold" onclick="Update(@item.Id)">Editar</button>
                    </td>
                    <td>
                        <button class="btn btn-outline-warning btn-sm" type="button" style="font-weight:bold" onclick="UpdateStatus(@item.Id)">Atender</button>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<button class="btn btn-outline-warning btn-block" type="button" style="font-weight:bold" onclick="Create()">Novo</button>

<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>

<script>
    var strValue = "@((string)ViewBag.message)";

    if (strValue !== null && strValue !== '')
    {
        swal("", strValue, "success");
    }
</script>

<script>
    function Update(id)
    {
        window.location.href = "../Schedulings/Update/" + id;
    }

    function UpdateStatus(id)
    {
        window.location.href = "../Schedulings/UpdateStatus/" + id;
    }

    function Create()
    {
        window.location.href = "../Schedulings/Create";
    }
</script>

JLLF.Presentation/Views/Schedulings/Update.cshtml
@model JLLF.Presentation.ViewModels.CompositeViewModel

@{
    ViewData["Title"] = "Agendamento";
}

<label style="font-weight:bold">Editar Agendamento</label>

<br />
<br />

<form asp-controller="Schedulings" asp-action="Update">
    <input asp-for="Id" type="hidden" value="@Model.Id" />
    <div class="form-row">
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Colaborador</label>
            <select asp-for="IdCollaboratorViewModel" class="form-control" value="@Model.ResponseCollaboratorsViewModel.Where(rcvm => rcvm.Id == Model.IdCollaboratorViewModel).First().Id">
                @{
                    foreach (var item in Model.ResponseCollaboratorsViewModel)
                    {
                        <option value="@item.Id">@item.Name</option>
                    }
                }
            </select>
        </div>
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Cliente</label>
            <select asp-for="IdCustomerViewModel" class="form-control" value="@Model.ResponseCustomersViewModel.Where(rcvm => rcvm.Id == Model.IdCustomerViewModel).First().Id">
                @{
                    foreach (var item in Model.ResponseCustomersViewModel)
                    {
                        <option value="@item.Id">@item.Name</option>
                    }
                }
            </select>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Serviço</label>
            <select asp-for="IdServiceProvidedViewModel" class="form-control" value="@Model.ResponseServicesProvidedViewModel.Where(rspvm => rspvm.Id == Model.IdServiceProvidedViewModel).First().Id">
                @{
                    foreach (var item in Model.ResponseServicesProvidedViewModel)
                    {
                        <option value="@item.Id">@item.Description</option>
                    }
                }
            </select>
        </div>
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Data e Horário</label>
            <input asp-for="DateTime" class="form-control" type="datetime-local" required value="@Model.DateTime" />
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12">
            <button class="btn btn-outline-warning btn-block" type="submit" style="font-weight:bold">Salvar</button>
        </div>
    </div>
</form>

JLLF.Presentation/Views/Schedulings/UpdateStatus.cshtml
@model JLLF.Presentation.ViewModels.CompositeViewModel

@{
    ViewData["Title"] = "Agendamento";
}

<label style="font-weight:bold">Deseja realmente marcar o agendamento como atendido?</label>

<br />
<br />

<form asp-controller="Schedulings" asp-action="UpdateStatus">
    <input asp-for="Id" type="hidden" value="@Model.Id" />
    <div class="form-row" hidden>
        <div class="form-group col-md-6" hidden>
            <label style="font-weight:bold" hidden>Colaborador</label>
            <select asp-for="IdCollaboratorViewModel" class="form-control" hidden value="@Model.ResponseCollaboratorsViewModel.Where(rcvm => rcvm.Id == Model.IdCollaboratorViewModel).First().Id">
                @{
                    foreach (var item in Model.ResponseCollaboratorsViewModel)
                    {
                        <option hidden value="@item.Id">@item.Name</option>
                    }
                }
            </select>
        </div>
        <div class="form-group col-md-6" hidden>
            <label style="font-weight:bold" hidden>Cliente</label>
            <select asp-for="IdCustomerViewModel" class="form-control" hidden value="@Model.ResponseCustomersViewModel.Where(rcvm => rcvm.Id == Model.IdCustomerViewModel).First().Id">
                @{
                    foreach (var item in Model.ResponseCustomersViewModel)
                    {
                        <option hidden value="@item.Id">@item.Name</option>
                    }
                }
            </select>
        </div>
    </div>
    <div class="form-row" hidden>
        <div class="form-group col-md-6" hidden>
            <label style="font-weight:bold" hidden>Serviço</label>
            <select asp-for="IdServiceProvidedViewModel" class="form-control" hidden value="@Model.ResponseServicesProvidedViewModel.Where(rspvm => rspvm.Id == Model.IdServiceProvidedViewModel).First().Id">
                @{
                    foreach (var item in Model.ResponseServicesProvidedViewModel)
                    {
                        <option hidden value="@item.Id">@item.Description</option>
                    }
                }
            </select>
        </div>
        <div class="form-group col-md-6" hidden>
            <label style="font-weight:bold" hidden>Data e Horário</label>
            <input asp-for="DateTime" class="form-control" type="hidden" required value="@Model.DateTime" />
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12">
            <button class="btn btn-outline-warning btn-block" type="submit" style="font-weight:bold">Sim</button>
        </div>
    </div>
</form>