JLLF.Presentation/ViewModels/CollaboratorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace JLLF.Presentation.ViewModels
{
    public class CollaboratorViewModel
    {
        public int? Id { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório!")]
        [MinLength(1, ErrorMessage = "Campo Deve Conter No Mínimo 1 Caracter!")]
        [MaxLength(255, ErrorMessage = "Campo Deve Conter No Máximo 255 Caracteres!")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório!")]
        [MinLength(8, ErrorMessage = "Campo Deve Conter No Mínimo 8 Caracteres - Feminino!")]
        [MaxLength(9, ErrorMessage = "Campo Deve Conter No Máximo 9 Caracteres - Masculino!")]
        public string Gender { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório!")]
        [StringLength(14, ErrorMessage = "Campo Deve Conter 14 Caracteres!", MinimumLength = 14)]
        [DisplayFormat(DataFormatString = "000.000.000-00")]
        public string CPF { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório!")]
        [StringLength(13, ErrorMessage = "Campo Deve Conter 13 Caracteres!", MinimumLength = 13)]
        [DisplayFormat(DataFormatString = "00 00000-0000")]
        public string TelephoneNumber { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório!")]
        [MinLength(1, ErrorMessage = "Campo Deve Conter No Mínimo 1 Caracter!")]
        [MaxLength(255, ErrorMessage = "Campo Deve Conter No Máximo 255 Caracteres!")]
        public string Function { get; set; }

        public DateTime? RegistrationDate { get; set; }

        public bool? Status { get; set; }
    }

    public class ResponseCollaboratorViewModel : CollaboratorViewModel
    {
        public virtual ICollection<SchedulingViewModel> SchedulingsViewModelListByCollaboratorViewModel { get; set; }
    }
}

JLLF.Presentation/Controllers/CollaboratorsController.cs
using JLLF.Domain.Interfaces.Services;
using JLLF.Domain.Validations;
using JLLF.Presentation.Mappings;
using JLLF.Presentation.Mappings.Responses;
using JLLF.Presentation.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace JLLF.Presentation.Controllers
{
    public class CollaboratorsController : Controller
    {
        private readonly ICollaboratorService _collaboratorService;
        private readonly CollaboratorViewModelMapping collaboratorViewModelMapping = new();
        private readonly ResponseCollaboratorViewModelMapping responseCollaboratorViewModelMapping = new();

        public CollaboratorsController(ICollaboratorService collaboratorService)
        {
            _collaboratorService = collaboratorService;
        }

        public IActionResult Index()
        {
            try
            {
                ViewBag.message = TempData["message"] as string;

                IList<ResponseCollaboratorViewModel> responseCollaboratorViewModels = responseCollaboratorViewModelMapping.ListConversion(_collaboratorService.FindAll());

                if (responseCollaboratorViewModels.Count > 0)
                    return View(responseCollaboratorViewModels);

                return RedirectToAction("Create");
            }
            catch (Exception)
            {
                return RedirectToAction("Create");
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CollaboratorViewModel collaboratorViewModel)
        {
            if (ModelState.IsValid)
            {
                collaboratorViewModel.RegistrationDate = DateTime.Now;
                collaboratorViewModel.Status = true;

                _collaboratorService.Create<CollaboratorValidation>(collaboratorViewModelMapping.Conversion(collaboratorViewModel));

                TempData["message"] = "Colaborador cadastrado com sucesso!".ToString();

                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Update(int id)
        {
            try
            {
                ResponseCollaboratorViewModel responseCollaboratorViewModel = responseCollaboratorViewModelMapping.Conversion(_collaboratorService.FindById(id));

                if (responseCollaboratorViewModel.Id > 0)
                    return View(responseCollaboratorViewModel);

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Update(CollaboratorViewModel collaboratorViewModel)
        {
            if (ModelState.IsValid)
            {
                collaboratorViewModel.RegistrationDate = DateTime.Now;
                collaboratorViewModel.Status = true;

                _collaboratorService.Update<CollaboratorValidation>(collaboratorViewModelMapping.Conversion(collaboratorViewModel));

                TempData["message"] = "Colaborador atualizado com sucesso!".ToString();

                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult UpdateStatus(int id)
        {
            try
            {
                ResponseCollaboratorViewModel responseCollaboratorViewModel = responseCollaboratorViewModelMapping.Conversion(_collaboratorService.FindById(id));

                if (responseCollaboratorViewModel.Id > 0)
                    return View(responseCollaboratorViewModel);

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult UpdateStatus(CollaboratorViewModel collaboratorViewModel)
        {
            if (ModelState.IsValid)
            {
                collaboratorViewModel.RegistrationDate = DateTime.Now;
                collaboratorViewModel.Status = false;

                _collaboratorService.Update<CollaboratorValidation>(collaboratorViewModelMapping.Conversion(collaboratorViewModel));

                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Details(int id)
        {
            try
            {
                ResponseCollaboratorViewModel responseCollaboratorViewModel = responseCollaboratorViewModelMapping.Conversion(_collaboratorService.FindById(id));

                if (responseCollaboratorViewModel.Id > 0)
                    return View(responseCollaboratorViewModel);

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }
    }
}

JLLF.Presentation/Views/Collaborators/Create.cshtml
@model JLLF.Presentation.ViewModels.CollaboratorViewModel

@{
    ViewData["Title"] = "Colaborador";
}

<label style="font-weight:bold">Inserir Colaborador</label>

<br />
<br />

<form asp-controller="Collaborators" asp-action="Create">
    <div class="form-group">
        <label style="font-weight:bold">Nome</label>
        <input asp-for="Name" class="form-control" type="text" />
        <span asp-validation-for="Name" class="text-danger" style="font-weight:bold"></span>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Gênero</label>
            <select asp-for="Gender" class="form-control">
                <option>Feminino</option>
                <option>Masculino</option>
            </select>
        </div>
        <div class="form-group col-md-6">
            <label style="font-weight:bold">CPF</label>
            <input asp-for="CPF" class="form-control" type="text" placeholder="Exemplo: 000.000.000-00" />
            <span asp-validation-for="CPF" class="text-danger" style="font-weight:bold"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Telefone</label>
            <input asp-for="TelephoneNumber" class="form-control" type="text" placeholder="Exemplo: 34 99999-9999" />
            <span asp-validation-for="TelephoneNumber" class="text-danger" style="font-weight:bold"></span>
        </div>
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Função</label>
            <input asp-for="Function" class="form-control" type="text" />
            <span asp-validation-for="Function" class="text-danger" style="font-weight:bold"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12">
            <button class="btn btn-outline-warning btn-block" type="submit" style="font-weight:bold">Salvar</button>
        </div>
    </div>
</form>

JLLF.Presentation/Views/Collaborators/Details.cshtml
@model JLLF.Presentation.ViewModels.ResponseCollaboratorViewModel

@{
    ViewData["Title"] = "Colaborador";
}

<label style="font-weight:bold">Detalhes do Colaborador</label>

<br />
<br />

<form asp-controller="Collaborators" asp-action="Details">
    <div class="form-group">
        <label style="font-weight:bold">Nome</label>
        <br />
        <label>@Model.Name</label>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Gênero</label>
            <br />
            <label>@Model.Gender</label>
        </div>
        <div class="form-group col-md-6">
            <label style="font-weight:bold">CPF</label>
            <br />
            <label>@Model.CPF</label>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Telefone</label>
            <br />
            <label>@Model.TelephoneNumber</label>
        </div>
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Função</label>
            <br />
            <label>@Model.Function</label>
        </div>
    </div>
</form>

JLLF.Presentation/Views/Collaborators/Index.cshtml
@model IList<JLLF.Presentation.ViewModels.ResponseCollaboratorViewModel>

@{
    ViewData["Title"] = "Colaboradores";
}

<label style="font-weight:bold">Colaboradores</label>

<br />
<br />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css" />

<table class="table table-responsive-sm">
    <thead>
        <tr>
            <th style="display:none">Código</th>
            <th>Nome</th>
            <th>Função</th>
            <th>Status</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var item in Model)
            {
                <tr>
                    <td style="display:none">@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.Function</td>
                    @if (@item.Status == true)
                     {
                        <td>Ativo</td>
                     }
                     else
                     {
                        <td>Inativo</td>
                     }
                    <td>
                        <button class="btn btn-outline-warning btn-sm" type="button" style="font-weight:bold" onclick="Details(@item.Id)">Detalhes</button>
                    </td>
                    <td>
                        <button class="btn btn-outline-warning btn-sm" type="button" style="font-weight:bold" onclick="Update(@item.Id)">Editar</button>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<button class="btn btn-outline-warning btn-block" type="button" style="font-weight:bold" onclick="Create()">Novo</button>

<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>

<script>
    var strValue = "@((string)ViewBag.message)";

    if (strValue !== null && strValue !== '')
    {
        swal("", strValue, "success");
    }
</script>

<script>
    function Details(id)
    {
        window.location.href = "../Collaborators/Details/" + id;
    }

    function Update(id)
    {
        window.location.href = "../Collaborators/Update/" + id;
    }

    function UpdateStatus(id)
    {
        window.location.href = "../Collaborators/UpdateStatus/" + id;
    }

    function Create()
    {
        window.location.href = "../Collaborators/Create";
    }
</script>

JLLF.Presentation/Views/Collaborators/Update.cshtml
@model JLLF.Presentation.ViewModels.ResponseCollaboratorViewModel

@{
    ViewData["Title"] = "Colaborador";
}

<label style="font-weight:bold">Editar Colaborador</label>

<br />
<br />

<form asp-controller="Collaborators" asp-action="Update">
    <input asp-for="Id" type="hidden" value="@Model.Id" />
    <div class="form-group">
        <label style="font-weight:bold">Nome</label>
        <input asp-for="Name" class="form-control" type="text" required value="@Model.Name" />
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Gênero</label>
            <select asp-for="Gender" class="form-control" value="@Model.Gender">
                <option>Feminino</option>
                <option>Masculino</option>
            </select>
        </div>
        <div class="form-group col-md-6">
            <label style="font-weight:bold">CPF</label>
            <input asp-for="CPF" class="form-control" type="text" placeholder="Exemplo: 000.000.000-00" required value="@Model.CPF" />
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Telefone</label>
            <input asp-for="TelephoneNumber" class="form-control" type="text" placeholder="Exemplo: 34 99999-9999" required value="@Model.TelephoneNumber" />
        </div>
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Função</label>
            <input asp-for="Function" class="form-control" type="text" required value="@Model.Function" />
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12">
            <button class="btn btn-outline-warning btn-block" type="submit" style="font-weight:bold">Salvar</button>
        </div>
    </div>
</form>

JLLF.Presentation/Views/Collaborators/UpdateStatus.cshtml
@model JLLF.Presentation.ViewModels.ResponseCollaboratorViewModel

@{
    ViewData["Title"] = "Colaborador";
}

<label style="font-weight:bold">Deseja realmente inativar o colaborador @Model.Name?</label>

<br />
<br />

<form asp-controller="Collaborators" asp-action="UpdateStatus">
    <input asp-for="Id" type="hidden" value="@Model.Id" />
    <div class="form-group" hidden>
        <label style="font-weight:bold" hidden>Nome</label>
        <input asp-for="Name" class="form-control" type="hidden" required value="@Model.Name" />
    </div>
    <div class="form-row" hidden>
        <div class="form-group col-md-6" hidden>
            <label style="font-weight:bold" hidden>Gênero</label>
            <select asp-for="Gender" class="form-control" hidden value="@Model.Gender">
                <option hidden>Feminino</option>
                <option hidden>Masculino</option>
            </select>
        </div>
        <div class="form-group col-md-6" hidden>
            <label style="font-weight:bold" hidden>CPF</label>
            <input asp-for="CPF" class="form-control" type="hidden" placeholder="Exemplo: 000.000.000-00" required value="@Model.CPF" />
        </div>
    </div>
    <div class="form-row" hidden>
        <div class="form-group col-md-6" hidden>
            <label style="font-weight:bold" hidden>Telefone</label>
            <input asp-for="TelephoneNumber" class="form-control" type="hidden" placeholder="Exemplo: 34 99999-9999" required value="@Model.TelephoneNumber" />
        </div>
        <div class="form-group col-md-6" hidden>
            <label style="font-weight:bold" hidden>Função</label>
            <input asp-for="Function" class="form-control" type="hidden" required value="@Model.Function" />
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12">
            <button class="btn btn-outline-warning btn-block" type="submit" style="font-weight:bold">Sim</button>
        </div>
    </div>
</form>