JLLF.Presentation/ViewModels/ReportViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace JLLF.Presentation.ViewModels
{
    public class ReportViewModel : CompositeViewModel
    {
        [Required(ErrorMessage = "Campo Obrigatório!")]
        public DateTime InitialDate { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório!")]
        public DateTime FinalDate { get; set; }
    }
}

JLLF.Presentation/Controllers/ReportsController.cs
using JLLF.Domain.Interfaces.Services;
using JLLF.Presentation.Mappings.Responses;
using JLLF.Presentation.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace JLLF.Presentation.Controllers
{
    public class ReportsController : Controller
    {
        private readonly ISchedulingService _schedulingService;
        private readonly ResponseSchedulingViewModelMapping responseSchedulingViewModelMapping = new();
        
        public ReportsController(ISchedulingService schedulingService)
        {
            _schedulingService = schedulingService;
        }

        public IActionResult Index()
        {
            ViewBag.message = TempData["message"] as string;

            return View();
        }

        public IActionResult ReadByPeriod()
        {
            ViewBag.message = TempData["message"] as string;

            return View();
        }

        public IActionResult ReportByPeriod(ReportViewModel reportViewModel)
        {
            try
            {
                IList<ResponseSchedulingViewModel> responseSchedulingViewModels = responseSchedulingViewModelMapping.ListConversion(_schedulingService.FindByPeriod(reportViewModel.InitialDate, reportViewModel.FinalDate));

                if (responseSchedulingViewModels.Count > 0)
                    return View(responseSchedulingViewModels);

                TempData["message"] = "Não há agendamentos entre as datas e horários informados!".ToString();

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }
    }
}

JLLF.Presentation/Views/Reports/Index.cshtml
@{
    ViewData["Title"] = "Relatório de Agendamentos";
}

<label style="font-weight:bold">Relatório De Agendamentos</label>

<br />
<br />

<button class="btn btn-outline-warning btn-block" type="button" style="font-weight:bold" onclick="ByPeriod()">Por Período</button>

<script>
    function ByPeriod()
    {
        window.location.href = "../Reports/ReadByPeriod";
    }
</script>

JLLF.Presentation/Views/Reports/ReadByPeriod.cshtml
@model JLLF.Presentation.ViewModels.ReportViewModel

@{
    ViewData["Title"] = "Relatório de Agendamentos por Período";
}

<label style="font-weight:bold">Relatório de Agendamentos por Período</label>

<br />
<br />

<form asp-controller="Reports" asp-action="ReportByPeriod">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Data Inicial</label>
            <input asp-for="InitialDate" class="form-control" type="datetime-local" required value="@DateTime.Now" />
            <span asp-validation-for="InitialDate" class="text-danger" style="font-weight:bold"></span>
        </div>   
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Data Final</label>
            <input asp-for="FinalDate" class="form-control" type="datetime-local" required value="@DateTime.Now" />
            <span asp-validation-for="FinalDate" class="text-danger" style="font-weight:bold"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12">
            <button class="btn btn-outline-warning btn-block" type="submit" style="font-weight:bold">Pesquisar</button>
        </div>
    </div>
</form>

JLLF.Presentation/Views/Reports/ReportByPeriod.cshtml
@model IList<JLLF.Presentation.ViewModels.ResponseSchedulingViewModel>

@{
    ViewData["Title"] = "Relatório de Agendamentos por Período";
}

<label style="font-weight:bold">Relatório de Agendamentos por Período</label>

<br />
<br />

<table class="table table-responsive-sm">
    <thead>
        <tr>
            <th style="display:none">Código</th>
            <th>Colaborador</th>
            <th>Cliente</th>
            <th>Serviço</th>
            <th>Data</th>
            <th>Horário</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var item in Model)
            {
                <tr>
                    <td style="display:none">@item.Id</td>
                    <td>@item.CollaboratorViewModel.Name</td>
                    <td>@item.CustomerViewModel.Name</td>
                    <td>@item.ServiceProvidedViewModel.Description</td>
                    <td>@item.DateTime.Date.ToShortDateString()</td>
                    <td>@item.DateTime.TimeOfDay</td>
                    @if (@item.Status == true)
                     {
                        <td>Atendido</td>
                     }
                     else
                     {
                        <td>Aguardando</td>
                     }
                </tr>
            }
        }
    </tbody>
</table>