JLLF.Presentation/ViewModels/CustomerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace JLLF.Presentation.ViewModels
{
    public class CustomerViewModel
    {
        public int? Id { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório!")]
        [MinLength(1, ErrorMessage = "Campo Deve Conter No Mínimo 1 Caracter!")]
        [MaxLength(255, ErrorMessage = "Campo Deve Conter No Máximo 255 Caracteres!")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório!")]
        [MinLength(8, ErrorMessage = "Campo Deve Conter No Mínimo 8 Caracteres - Feminino!")]
        [MaxLength(9, ErrorMessage = "Campo Deve Conter No Máximo 9 Caracteres - Masculino!")]
        public string Gender { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório!")]
        [StringLength(14, ErrorMessage = "Campo Deve Conter 14 Caracteres!", MinimumLength = 14)]
        [DisplayFormat(DataFormatString = "000.000.000-00")]
        public string CPF { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório!")]
        [StringLength(13, ErrorMessage = "Campo Deve Conter 13 Caracteres!", MinimumLength = 13)]
        [DisplayFormat(DataFormatString = "00 00000-0000")]
        public string TelephoneNumber { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório!")]
        [MinLength(1, ErrorMessage = "Campo Deve Conter No Mínimo 1 Caracter!")]
        [MaxLength(255, ErrorMessage = "Campo Deve Conter No Máximo 255 Caracteres!")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessage = "E-mail Em Formato Inválido!")]
        public string EmailAddress { get; set; }

        public DateTime? RegistrationDate { get; set; }

        public bool? Status { get; set; }
    }

    public class ResponseCustomerViewModel : CustomerViewModel
    {
        public virtual ICollection<SchedulingViewModel> SchedulingsViewModelListByCustomerViewModel { get; set; }
    }
}

JLLF.Presentation/Controllers/CustomersController.cs
using JLLF.Domain.Interfaces.Services;
using JLLF.Domain.Validations;
using JLLF.Presentation.Mappings;
using JLLF.Presentation.Mappings.Responses;
using JLLF.Presentation.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace JLLF.Presentation.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ICustomerService _customerService;
        private readonly CustomerViewModelMapping customerViewModelMapping = new();
        private readonly ResponseCustomerViewModelMapping responseCustomerViewModelMapping = new();

        public CustomersController(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        public IActionResult Index()
        {
            try
            {
                ViewBag.message = TempData["message"] as string;

                IList<ResponseCustomerViewModel> responseCustomerViewModels = responseCustomerViewModelMapping.ListConversion(_customerService.FindAll());

                if (responseCustomerViewModels.Count > 0)
                    return View(responseCustomerViewModels);

                return RedirectToAction("Create");
            }
            catch (Exception)
            {
                return RedirectToAction("Create");
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CustomerViewModel customerViewModel)
        {
            if (ModelState.IsValid)
            {
                customerViewModel.RegistrationDate = DateTime.Now;
                customerViewModel.Status = true;

                _customerService.Create<CustomerValidation>(customerViewModelMapping.Conversion(customerViewModel));

                TempData["message"] = "Cliente cadastrado com sucesso!".ToString();

                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Update(int id)
        {
            try
            {
                ResponseCustomerViewModel responseCustomerViewModel = responseCustomerViewModelMapping.Conversion(_customerService.FindById(id));

                if (responseCustomerViewModel.Id > 0)
                    return View(responseCustomerViewModel);

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Update(CustomerViewModel customerViewModel)
        {
            if (ModelState.IsValid)
            {
                customerViewModel.RegistrationDate = DateTime.Now;
                customerViewModel.Status = true;

                _customerService.Update<CustomerValidation>(customerViewModelMapping.Conversion(customerViewModel));

                TempData["message"] = "Cliente atualizado com sucesso!".ToString();

                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult UpdateStatus(int id)
        {
            try
            {
                ResponseCustomerViewModel responseCustomerViewModel = responseCustomerViewModelMapping.Conversion(_customerService.FindById(id));

                if (responseCustomerViewModel.Id > 0)
                    return View(responseCustomerViewModel);

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult UpdateStatus(CustomerViewModel customerViewModel)
        {
            if (ModelState.IsValid)
            {
                customerViewModel.RegistrationDate = DateTime.Now;
                customerViewModel.Status = false;

                _customerService.Update<CustomerValidation>(customerViewModelMapping.Conversion(customerViewModel));

                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Details(int id)
        {
            try
            {
                ResponseCustomerViewModel responseCustomerViewModel = responseCustomerViewModelMapping.Conversion(_customerService.FindById(id));

                if (responseCustomerViewModel.Id > 0)
                    return View(responseCustomerViewModel);

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }
    }
}

JLLF.Presentation/Views/Customers/Create.cshtml
@model JLLF.Presentation.ViewModels.CustomerViewModel

@{
    ViewData["Title"] = "Cliente";
}

<label style="font-weight:bold">Inserir Cliente</label>

<br />
<br />

<form asp-controller="Customers" asp-action="Create">
    <div class="form-group">
        <label style="font-weight:bold">Nome</label>
        <input asp-for="Name" class="form-control" type="text" />
        <span asp-validation-for="Name" class="text-danger" style="font-weight:bold"></span>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Gênero</label>
            <select asp-for="Gender" class="form-control">
                <option>Feminino</option>
                <option>Masculino</option>
            </select>
        </div>
        <div class="form-group col-md-6">
            <label style="font-weight:bold">CPF</label>
            <input asp-for="CPF" class="form-control" type="text" placeholder="Exemplo: 000.000.000-00" />
            <span asp-validation-for="CPF" class="text-danger" style="font-weight:bold"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Telefone</label>
            <input asp-for="TelephoneNumber" class="form-control" type="text" placeholder="Exemplo: 34 99999-9999" />
            <span asp-validation-for="TelephoneNumber" class="text-danger" style="font-weight:bold"></span>
        </div>
        <div class="form-group col-md-6">
            <label style="font-weight:bold">E-mail</label>
            <input asp-for="EmailAddress" class="form-control" type="text" placeholder="Exemplo: contato@contato.com.br" />
            <span asp-validation-for="EmailAddress" class="text-danger" style="font-weight:bold"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12">
            <button class="btn btn-outline-warning btn-block" type="submit" style="font-weight:bold">Salvar</button>
        </div>
    </div>
</form>

JLLF.Presentation/Views/Customers/Details.cshtml
@model JLLF.Presentation.ViewModels.ResponseCustomerViewModel

@{
    ViewData["Title"] = "Cliente";
}

<label style="font-weight:bold">Detalhes do Cliente</label>

<br />
<br />

<form asp-controller="Customers" asp-action="Details">
    <div class="form-group">
        <label style="font-weight:bold">Nome</label>
        <br />
        <label>@Model.Name</label>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Gênero</label>
            <br />
            <label>@Model.Gender</label>
        </div>
        <div class="form-group col-md-6">
            <label style="font-weight:bold">CPF</label>
            <br />
            <label>@Model.CPF</label>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Telefone</label>
            <br />
            <label>@Model.TelephoneNumber</label>
        </div>
        <div class="form-group col-md-6">
            <label style="font-weight:bold">E-mail</label>
            <br />
            <label>@Model.EmailAddress</label>
        </div>
    </div>
</form>

JLLF.Presentation/Views/Customers/Index.cshtml
@model IList<JLLF.Presentation.ViewModels.ResponseCustomerViewModel>

@{
    ViewData["Title"] = "Clientes";
}

<label style="font-weight:bold">Clientes</label>

<br />
<br />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css" />

<table class="table table-responsive-sm">
    <thead>
        <tr>
            <th style="display:none">Código</th>
            <th>Nome</th>
            <th>Status</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var item in Model)
            {
                <tr>
                    <td style="display:none">@item.Id</td>
                    <td>@item.Name</td>
                    @if (@item.Status == true)
                     {
                        <td>Ativo</td>
                     }
                     else
                     {
                        <td>Inativo</td>
                     }
                    <td>
                    <td>
                        <button class="btn btn-outline-warning btn-sm" type="button" style="font-weight:bold" onclick="Details(@item.Id)">Detalhes</button>
                    </td>
                    <td>
                        <button class="btn btn-outline-warning btn-sm" type="button" style="font-weight:bold" onclick="Update(@item.Id)">Editar</button>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<button class="btn btn-outline-warning btn-block" type="button" style="font-weight:bold" onclick="Create()">Novo</button>

<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>

<script>
    var strValue = "@((string)ViewBag.message)";

    if (strValue !== null && strValue !== '')
    {
        swal("", strValue, "success");
    }
</script>

<script>
    function Details(id)
    {
        window.location.href = "../Customers/Details/" + id;
    }

    function Update(id)
    {
        window.location.href = "../Customers/Update/" + id;
    }

    function UpdateStatus(id)
    {
        window.location.href = "../Customers/UpdateStatus/" + id;
    }

    function Create()
    {
        window.location.href = "../Customers/Create";
    }
</script>

JLLF.Presentation/Views/Customers/Update.cshtml
@model JLLF.Presentation.ViewModels.ResponseCustomerViewModel

@{
    ViewData["Title"] = "Cliente";
}

<label style="font-weight:bold">Editar Cliente</label>

<br />
<br />

<form asp-controller="Customers" asp-action="Update">
    <input asp-for="Id" type="hidden" value="@Model.Id" />
    <div class="form-group">
        <label style="font-weight:bold">Nome</label>
        <input asp-for="Name" class="form-control" type="text" required value="@Model.Name" />
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Gênero</label>
            <select asp-for="Gender" class="form-control" value="@Model.Gender">
                <option>Feminino</option>
                <option>Masculino</option>
            </select>
        </div>
        <div class="form-group col-md-6">
            <label style="font-weight:bold">CPF</label>
            <input asp-for="CPF" class="form-control" type="text" placeholder="Exemplo: 000.000.000-00" required value="@Model.CPF" />
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label style="font-weight:bold">Telefone</label>
            <input asp-for="TelephoneNumber" class="form-control" type="text" placeholder="Exemplo: 34 99999-9999" required value="@Model.TelephoneNumber" />
        </div>
        <div class="form-group col-md-6">
            <label style="font-weight:bold">E-mail</label>
            <input asp-for="EmailAddress" class="form-control" type="text" placeholder="Exemplo: contato@contato.com.br" required value="@Model.EmailAddress" />
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12">
            <button class="btn btn-outline-warning btn-block" type="submit" style="font-weight:bold">Salvar</button>
        </div>
    </div>
</form>

JLLF.Presentation/Views/Customers/UpdateStatus.cshtml
@model JLLF.Presentation.ViewModels.ResponseCustomerViewModel

@{
    ViewData["Title"] = "Cliente";
}

<label style="font-weight:bold">Deseja realmente inativar o cliente @Model.Name?</label>

<br />
<br />

<form asp-controller="Customers" asp-action="UpdateStatus">
    <input asp-for="Id" type="hidden" value="@Model.Id" />
    <div class="form-group" hidden>
        <label style="font-weight:bold" hidden>Nome</label>
        <input asp-for="Name" class="form-control" type="hidden" required value="@Model.Name" />
    </div>
    <div class="form-row" hidden>
        <div class="form-group col-md-6" hidden>
            <label style="font-weight:bold" hidden>Gênero</label>
            <select asp-for="Gender" class="form-control" hidden value="@Model.Gender">
                <option hidden>Feminino</option>
                <option hidden>Masculino</option>
            </select>
        </div>
        <div class="form-group col-md-6" hidden>
            <label style="font-weight:bold" hidden>CPF</label>
            <input asp-for="CPF" class="form-control" type="hidden" placeholder="Exemplo: 000.000.000-00" required value="@Model.CPF" />
        </div>
    </div>
    <div class="form-row" hidden>
        <div class="form-group col-md-6" hidden>
            <label style="font-weight:bold" hidden>Telefone</label>
            <input asp-for="TelephoneNumber" class="form-control" type="hidden" placeholder="Exemplo: 34 99999-9999" required value="@Model.TelephoneNumber" />
        </div>
        <div class="form-group col-md-6" hidden>
            <label style="font-weight:bold" hidden>E-mail</label>
            <input asp-for="EmailAddress" class="form-control" type="hidden" placeholder="Exemplo: contato@contato.com.br" required value="@Model.EmailAddress" />
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12">
            <button class="btn btn-outline-warning btn-block" type="submit" style="font-weight:bold">Sim</button>
        </div>
    </div>
</form>